version: '3'

services:

  app:
    build: php
    container_name: app
    volumes:
      - ../:/var/www/application

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/application
      - ../docker/nginx:/etc/nginx/conf.d/